(defun list-keys-with-trait (trait hashtable key-subindex)
  (let ((keylist nil))
    (flet ((discriminator (hkey hval)
	     (when (funcall trait (nth key-subindex hkey))
	       (push hkey keylist))))
      (maphash #'discriminator hashtable)
      keylist)))

(defun count-keys-with-trait (trait hashtable key-subindex)
  (let ((count 0))
    (flet ((discriminator (hkey hval)
	     (when (funcall trait (nth key-subindex hkey))
	       (incf count 1))))
      (maphash #'discriminator hashtable)
      count)))
